services:
  db:
    image: postgres:15.7
    container_name: metrics-db
    hostname: db
    ports:
      - "5432:5432"
    volumes:
      - metrics-db_data:/var/lib/postgresql/data
      - metrics-db_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres.env
    # command: "-c log_statement=all"

  olap:
    image: clickhouse/clickhouse-server:25.6
    container_name: metrics-olap
    hostname: olap
    ports:
      - "8123:8123"
      - "8124:9000"
    volumes:
      - metrics-olap_data:/var/lib/clickhouse
      - metrics-olap_server:/var/lib/clickhouse-server
    env_file:
      - ./.envs/.local/.clickhouse.env

  redis:
    image: redis:7.0.15
    container_name: metrics-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - metrics-redis_data:/data
    env_file:
      - ./.envs/.local/.django.env

  storage:
    image: minio/minio:latest
    container_name: storage
    hostname: storage
    command: server /data --console-address ":9001"
    ports:
      - "9010:9000" # S3 API
      - "9011:9001" # Web console
    env_file:
      - ./.envs/.local/.minio.env
    volumes:
      - minio_data:/data

  api: &api
    build:
      context: .
      args:
        - DEV=true
    image: mosquito-alert/metrics-api
    container_name: metrics-api
    hostname: api
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/app
      - shared_temp:/shared_temp
    env_file:
      - ./.envs/.local/.django.env
      - ./.envs/.local/.postgres.env
      - ./.envs/.local/.clickhouse.env
    healthcheck:
      test: "curl -f http://localhost:8000/ping/ || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - db
      - redis
    command: /scripts/start

  worker:
    <<: *api
    container_name: metrics-worker
    hostname: worker
    ports: []
    command: /scripts/start_worker

  worker_flower:
    <<: *api
    container_name: metrics-flower
    hostname: flower
    ports:
      - "5556:5555"
    command: /scripts/start_flower


volumes:
  shared_temp:
  metrics-db_data:
  metrics-db_data_backups:
  metrics-olap_data:
  metrics-olap_server:
  metrics-redis_data:
  minio_data:

