# Generated by Django 5.2.4 on 2025-08-12 07:51

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import src.utils.postgresTypes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the metric.', max_length=255, unique=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricPredictionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='The date and time of the execution.', unique=True, verbose_name='Time')),
                ('success_percentage', models.FloatField(default=0, help_text='The percentage of success of the execution.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Success percentage')),
            ],
            options={
                'verbose_name': 'Metric Prediction Progress',
                'verbose_name_plural': 'Metric Prediction Progressses',
                'ordering': ['time'],
                'indexes': [models.Index(fields=['-time'], name='metrics_met_time_47cc1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_index', src.utils.postgresTypes.H3Field(help_text='The H3 index of the metric value boundary, used for spatial queries. This is stored as a bigInt to avoid issues with large indices, so it should be converted to/from hex strings if necessary.', verbose_name='H3 Index')),
                ('last_training_date', models.DateTimeField(help_text='The last value date used to train the model.', verbose_name='Last Training Date')),
                ('weights', models.JSONField(blank=True, help_text='The predictor model itself, serialized as JSON.', null=True, verbose_name='Weights')),
                ('yearly_seasonality', django.contrib.postgres.fields.ArrayField(base_field=src.utils.postgresTypes.RealField(), blank=True, help_text='The predicted yearly seasonality for the metric.', null=True, size=365, verbose_name='Yearly Seasonality')),
                ('weekly_seasonality', django.contrib.postgres.fields.ArrayField(base_field=src.utils.postgresTypes.RealField(), blank=True, help_text='The predicted weekly seasonality for the metric.', null=True, size=7, verbose_name='Weekly Seasonality')),
                ('daily_seasonality', django.contrib.postgres.fields.ArrayField(base_field=src.utils.postgresTypes.RealField(), blank=True, help_text='The predicted daily seasonality for the metric.', null=True, size=24, verbose_name='Daily Seasonality')),
                ('trend', django.contrib.postgres.fields.ArrayField(base_field=src.utils.postgresTypes.RealField(), blank=True, help_text='The predicted trend for the metric.', null=True, size=None, verbose_name='Trend')),
                ('metric', models.ForeignKey(help_text='The metric associated to the predictor.', on_delete=django.db.models.deletion.CASCADE, related_name='predictors', to='metrics.metric', verbose_name='Metric')),
            ],
            options={
                'verbose_name': 'Predictor',
                'verbose_name_plural': 'Predictors',
                'ordering': ['metric', 'h3_index', '-last_training_date'],
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('h3_index', src.utils.postgresTypes.H3Field(help_text='The H3 index of the metric value boundary, used for spatial queries. This is stored as a bigInt to avoid issues with large indices, so it should be converted to/from hex strings if necessary.', verbose_name='H3 Index')),
                ('pk', models.CompositePrimaryKey('metric', 'h3_index', 'time', blank=True, editable=False, help_text='The primary key of the metric value, composed by the metric, h3 index and time.', primary_key=True, serialize=False, verbose_name='Primary Key')),
                ('time', models.DateTimeField(help_text='The time in which the raw value was recorded.', verbose_name='Time')),
                ('value', src.utils.postgresTypes.RealField(help_text='The actual value of the raw data.', verbose_name='Value')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Reanalysis'), (2, 'Forecast')], help_text='The type of the raw value.', verbose_name='Type')),
                ('predicted_value', src.utils.postgresTypes.RealField(blank=True, help_text='The predicted value.', null=True, verbose_name='Value')),
                ('lower_confidence_band', src.utils.postgresTypes.RealField(blank=True, help_text='The lower confidence band of the predicted value.', null=True, verbose_name='Lower Confidence Band')),
                ('upper_confidence_band', src.utils.postgresTypes.RealField(blank=True, help_text='The upper confidence band of the predicted value.', null=True, verbose_name='Upper Confidence Band')),
                ('anomaly_degree', src.utils.postgresTypes.RealField(blank=True, help_text='The degree of the anomaly, a range of values that starts on -1 (a lower anomaly of the highest degree) and ends on +1 (a upper anomaly of the highest degree). The 0 value means that there is no anomaly. This value will be estimated at creation.', null=True, verbose_name='Anomaly Degree')),
                ('metric', models.ForeignKey(help_text='The metric associated to the value.', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='metrics.metric', verbose_name='Metric')),
                ('predictor', models.ForeignKey(blank=True, help_text='The predictor associated to the predicted value.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='metrics.predictor', verbose_name='Predictor')),
            ],
            options={
                'verbose_name': 'Value',
                'verbose_name_plural': 'Values',
                'ordering': ['metric', 'h3_index', '-time'],
            },
        ),
        migrations.CreateModel(
            name='PredictorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_seasonality', models.BooleanField(default=True, help_text='Whether the predictor should consider yearly seasonality.', verbose_name='Yearly Seasonality')),
                ('weekly_seasonality', models.BooleanField(default=False, help_text='Whether the predictor should consider weekly seasonality.', verbose_name='Weekly Seasonality')),
                ('daily_seasonality', models.BooleanField(default=False, help_text='Whether the predictor should consider daily seasonality.', verbose_name='Daily Seasonality')),
                ('growth', models.CharField(default='logistic', help_text='The growth model to use for the predictor.', max_length=32, verbose_name='Growth')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether the predictor is enabled or not.If disabled, the predictor will not be used for making predictions.', verbose_name='Is Enabled')),
                ('metric', models.OneToOneField(help_text='The metric associated to the predictor configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='predictor_config', to='metrics.metric', verbose_name='Metric')),
            ],
            options={
                'verbose_name': 'Predictor Config',
                'verbose_name_plural': 'Predictor Configs',
            },
        ),
        migrations.AddIndex(
            model_name='predictor',
            index=models.Index(fields=['metric', 'h3_index', 'last_training_date'], name='metrics_pre_metric__64a249_idx'),
        ),
        migrations.AddConstraint(
            model_name='predictor',
            constraint=models.UniqueConstraint(fields=('metric', 'h3_index', 'last_training_date'), name='unique_predictor'),
        ),
        migrations.AddIndex(
            model_name='metricvalue',
            index=models.Index(fields=['metric', 'h3_index', 'time'], name='metrics_met_metric__ade9b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.UniqueConstraint(fields=('metric', 'h3_index', 'time'), name='unique_metric'),
        ),
        migrations.AddConstraint(
            model_name='metricvalue',
            constraint=models.CheckConstraint(condition=src.utils.postgresTypes.H3IsValidCell(models.F('h3_index')), name='h3_index_must_be_valid'),
        ),
    ]
