# Generated by Django 5.2.4 on 2025-09-24 08:40

import clickhouse_backend.models
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.manager
import django_lifecycle.mixins
import src.utils.database_features
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the metric.', max_length=255, unique=True, verbose_name='Name')),
                ('code', models.SlugField(help_text='The code of the metric, used for identification purposes. Example: bites.', max_length=32, unique=True, verbose_name='Code')),
                ('time_dimension_step', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Daily'), (2, 'Hourly')], default=1, help_text='The time dimension step for the metric. Minutes are the smallest unit.', verbose_name='Time Dimension Step')),
                ('is_predictable', models.BooleanField(help_text='Whether the metric is predictable or not. If true, the metric will have a predictor associated to it, and the values will be predicted.', verbose_name='Is Predictable')),
                ('h3_resolution', models.PositiveSmallIntegerField(default=6, help_text='The H3 resolution of the metric. This is used to determine the H3 index of the metric.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='H3 Resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_id', clickhouse_backend.models.Int64Field(help_text='The ID of the metric associated to the value.', verbose_name='Metric ID')),
                ('h3_index', clickhouse_backend.models.FixedStringField(blank=True, help_text='The H3 index of the metric value boundary, used for spatial queries. This is stored as a bigInt to avoid issues with large indices, so it should be converted to/from hex strings if necessary.', max_bytes=15, verbose_name='H3 Index')),
                ('time', clickhouse_backend.models.DateTimeField(blank=True, help_text='The time in which the raw value was recorded. Maximum precision is one minute.', verbose_name='Time')),
                ('value', clickhouse_backend.models.Float32Field(blank=True, help_text='The actual value of the raw data.', null=True, verbose_name='Value')),
                ('predicted_value', clickhouse_backend.models.Float32Field(blank=True, help_text='The predicted value.', null=True, verbose_name='Value')),
                ('lower_confidence_band', clickhouse_backend.models.Float32Field(blank=True, help_text='The lower confidence band of the predicted value.', null=True, verbose_name='Lower Confidence Band')),
                ('upper_confidence_band', clickhouse_backend.models.Float32Field(blank=True, help_text='The upper confidence band of the predicted value.', null=True, verbose_name='Upper Confidence Band')),
                ('anomaly_degree', clickhouse_backend.models.Float32Field(blank=True, help_text='The degree of the anomaly, a range of values that starts on -1 (a lower anomaly of the highest degree) and ends on +1 (a upper anomaly of the highest degree). The 0 value means that there is no anomaly. This value will be estimated at creation.', null=True, verbose_name='Anomaly Degree')),
            ],
            options={
                'verbose_name': 'Metric Value',
                'verbose_name_plural': 'Metric Values',
                'ordering': ['metric_id', 'h3_index', '-time'],
                'engine': clickhouse_backend.models.ReplacingMergeTree(index_granularity=4096, order_by=['metric_id', 'h3_index', 'time'], partition_by=[clickhouse_backend.models.toYYYYMM('time')], primary_key=['metric_id', 'h3_index', 'time']),
                'indexes': [clickhouse_backend.models.Index(fields=['h3_index'], granularity=32, name='h3_index_bloom_filter_index', type=clickhouse_backend.models.BloomFilter())],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__isnull', False), ('predicted_value__isnull', False), _connector='OR'), name='value_or_predicted_value_must_be_present')],
            },
            bases=(models.Model, django_lifecycle.mixins.LifecycleModelMixin),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PredictorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearly_seasonality', models.BooleanField(default=True, help_text='Whether the predictor should consider yearly seasonality.', verbose_name='Yearly Seasonality')),
                ('weekly_seasonality', models.BooleanField(default=False, help_text='Whether the predictor should consider weekly seasonality.', verbose_name='Weekly Seasonality')),
                ('daily_seasonality', models.BooleanField(default=False, help_text='Whether the predictor should consider daily seasonality.', verbose_name='Daily Seasonality')),
                ('growth', models.CharField(default='logistic', help_text='The growth model to use for the predictor.', max_length=32, verbose_name='Growth')),
                ('metric', models.OneToOneField(help_text='The metric associated to the predictor configuration.', on_delete=django.db.models.deletion.CASCADE, related_name='predictor_config', to='metrics.metric', verbose_name='Metric')),
            ],
            options={
                'verbose_name': 'Predictor Config',
                'verbose_name_plural': 'Predictor Configs',
            },
        ),
        migrations.CreateModel(
            name='MetricSpatialDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h3_index', models.CharField(help_text='The H3 index of the region.', max_length=16, verbose_name='H3 Index')),
                ('trend', django.contrib.postgres.fields.ArrayField(base_field=src.utils.database_features.RealField(), blank=True, help_text='The predicted trend for the metric.', null=True, size=None, verbose_name='Trend')),
                ('yearly_seasonality', django.contrib.postgres.fields.ArrayField(base_field=src.utils.database_features.RealField(), blank=True, help_text='The predicted yearly seasonality for the metric.', null=True, size=365, verbose_name='Yearly Seasonality')),
                ('weekly_seasonality', django.contrib.postgres.fields.ArrayField(base_field=src.utils.database_features.RealField(), blank=True, help_text='The predicted weekly seasonality for the metric.', null=True, size=7, verbose_name='Weekly Seasonality')),
                ('daily_seasonality', django.contrib.postgres.fields.ArrayField(base_field=src.utils.database_features.RealField(), blank=True, help_text='The predicted daily seasonality for the metric.', null=True, size=24, verbose_name='Daily Seasonality')),
                ('metric', models.ForeignKey(help_text='The metric associated to the spatial dimensions.', on_delete=django.db.models.deletion.CASCADE, related_name='spatial_dimensions', to='metrics.metric', verbose_name='Metric')),
            ],
            options={
                'verbose_name': 'Metric Spatial Dimension',
                'verbose_name_plural': 'Metric Spatial Dimensions',
                'ordering': ['metric', 'h3_index'],
                'indexes': [models.Index(fields=['metric', 'h3_index'], name='metrics_met_metric__f0d68b_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric', 'h3_index'), name='spatial_dimension_unique_metric_h3_index')],
            },
        ),
        migrations.CreateModel(
            name='MetricTimeDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(help_text='The date and time of the metric values.', verbose_name='Time')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Reanalysis'), (2, 'Forecast')], help_text='The type of the raw value.', verbose_name='Type')),
                ('total_cells', models.IntegerField(blank=True, default=0, help_text='The total number of cells.', verbose_name='Total Cells')),
                ('total_cells_predicted', models.IntegerField(blank=True, help_text='The total number of cells processed with a prediction.', null=True, verbose_name='Total Cells Completed')),
                ('prediction_progress', models.GeneratedField(db_persist=True, expression=models.Case(models.When(then=models.Value(None), total_cells_predicted__isnull=True), default=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('total_cells_predicted'), '*', models.Value(1.0)), '/', models.F('total_cells'))), help_text='The percentage of cells completed with a prediction.', null=True, output_field=src.utils.database_features.RealField(), validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Prediction Progress')),
                ('metric', models.ForeignKey(help_text='The metric associated to the time dimensions.', on_delete=django.db.models.deletion.CASCADE, related_name='time_dimensions', to='metrics.metric', verbose_name='Metric')),
            ],
            options={
                'verbose_name': 'Metric Time Dimension',
                'verbose_name_plural': 'Metric Time Dimensions',
                'ordering': ['metric', '-time'],
                'indexes': [models.Index(fields=['metric', 'time'], name='metrics_met_metric__3a05a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('metric', 'time'), name='unique_metric_time_dimension')],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
